SFT_huggingface_card = 'Helsinki-NLP/opus-mt-en-zh'
task = 'wmt19'
src_tgt = 'zh-en'
train_data_path = './data/train.csv'
val_data_path = './data/val.csv'
num_data = 300000
src, tgt = 'en', 'zh'
rm_model_path = './rm_model'
rl_model_path = './rl_model'
num_sample = 8
batch_size = 4
init_beta = 0.2
init_gamma = 0.0
kl_target = 1
k_beta = 0.1
epochs = 20
train_rm_lr = 1e-5
train_ppo_lr = 1e-6
